name: CMake Nightly
on:
  schedule: [{ cron: "49 05 * * *" }]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        conf:
          - build-name: Ubuntu
            runs-on: ubuntu-24.04
            container:
              image: ghcr.io/purplekarrot/clang-builder:master
              options: --hostname clang-builder
          - build-name: MacOS
            runs-on: macos-15
          - build-name: Windows
            runs-on: windows-2025

    name: ${{ matrix.conf.build-name }}
    runs-on: ${{ matrix.conf.runs-on }}
    container: ${{ matrix.conf.container }}

    steps:
      - name: Checkout Source Code
        id: checkout
        uses: actions/checkout@v4
        with:
          repository: Kitware/CMake

      - name: Visual Studio build environment
        uses: seanmiddleditch/gha-setup-vsdevenv@master
        if: matrix.conf.runs-on == 'windows-2025'

      - name: Dashboard Build
        uses: chorse-dev/cmake-action@master
        with:
          build-name: ${{ matrix.conf.build-name }}
          change-id: ${{ steps.checkout.outputs.commit }}
          cmake-generator: Ninja
          submit-url: "https://chorse.dev/api/submit?project=CMake"
