name: CMake Nightly
on:
  push:
    paths:
      - ".github/workflows/cmake.yml"
  schedule:
    - cron: "49 06 * * *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        conf:
          - build-name: Ubuntu
            runs-on: ubuntu-latest
            cmake-generator: Unix Makefiles
          - build-name: MacOS
            runs-on: macos-latest
            cmake-generator: Xcode
          - build-name: Windows
            runs-on: windows-2022
            cmake-generator: Visual Studio 17 2022

    name: ${{ matrix.conf.build-name }} (${{ matrix.conf.cmake-generator }})
    runs-on: ${{ matrix.conf.runs-on }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          repository: Kitware/CMake

      - name: Dashboard Build
        uses: purpleKarrot/cmake-action@master
        with:
          build-name: ${{ matrix.conf.build-name }}
          cmake-generator: ${{ matrix.conf.cmake-generator }}
          submit-url: "https://ci.purplekarrot.net/api/submit?project=CMake"
