name: CMake Nightly
on:
  schedule: [{ cron: "49 05 * * *" }]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        conf:
          - build-name: Ubuntu
            runs-on: ubuntu-24.04
            container:
              image: ghcr.io/purplekarrot/clang-builder:master
              options: --hostname clang-builder
          - build-name: MacOS
            runs-on: macos-15
          - build-name: Windows
            runs-on: windows-2025
        proj:
          - name: CMake
            repository: https://gitlab.kitware.com/cmake/cmake.git
          - name: KWsys
            repository: https://gitlab.kitware.com/purpleKarrot/kwsys.git

    name: ${{ matrix.proj.name }} ${{ matrix.conf.build-name }}
    runs-on: ${{ matrix.conf.runs-on }}
    container: ${{ matrix.conf.container }}

    steps:
      - name: Checkout Source Code
        id: checkout
        run: |
          git clone --depth 1 ${{ matrix.proj.repository }} .
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Visual Studio build environment
        uses: seanmiddleditch/gha-setup-vsdevenv@master
        if: matrix.conf.runs-on == 'windows-2025'

      - name: Dashboard Build
        uses: chorse-dev/cmake-action@master
        with:
          build-name: ${{ matrix.conf.build-name }}
          change-id: ${{ steps.checkout.outputs.commit }}
          cmake-generator: Ninja
